# Generated by Django 3.0.3 on 2021-06-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S3upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_subject', models.CharField(max_length=200)),
                ('board_content', models.TextField()),
                ('board_date', models.DateTimeField(auto_now_add=True)),
                ('mem_name', models.TextField(max_length=20)),
                ('board_emo', models.TextField(max_length=100)),
                ('board_img', models.TextField(max_length=100)),
                ('board_tag', models.TextField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.TextField()),
                ('answer_date', models.DateTimeField()),
                ('mem_name', models.TextField(max_length=20)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Write')),
            ],
        ),
    ]
