# Generated by Django 3.0.5 on 2021-04-23 11:48

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Write',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_subject', models.CharField(max_length=200)),
                ('board_content', models.TextField()),
                ('board_date', models.DateTimeField()),
                ('mem_name', models.CharField(max_length=20)),
                ('board_emo', djongo.models.fields.JSONField(max_length=20)),
                ('board_tag', djongo.models.fields.JSONField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer_content', models.TextField()),
                ('Answer_date', models.DateTimeField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Write')),
            ],
        ),
    ]
