# Generated by Django 3.0.5 on 2021-05-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Answer_content',
            new_name='answer_content',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='Answer_date',
            new_name='answer_date',
        ),
    ]
