# Generated by Django 3.0.5 on 2021-05-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20210521_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='board_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='write',
            name='board_emo',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='write',
            name='board_tag',
            field=models.TextField(max_length=20),
        ),
    ]
